# Generated by Django 5.0.6 on 2024-07-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metatag',
            old_name='page_code',
            new_name='slug',
        ),
    ]
