# Generated by Django 5.0.6 on 2024-07-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='images/service', verbose_name='Image')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Category of a service',
                'verbose_name_plural': 'Categories of a service',
            },
        ),
    ]
