# Generated by Django 5.0.6 on 2024-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price2'),
        ),
    ]
