"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import decouple

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = decouple.config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = decouple.config('DEBUG') == 'True'

ALLOWED_HOSTS = [host.strip() for host in decouple.config('ALLOWED_HOSTS').split(',')]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_ckeditor_5',

    'staff',
    'service',
    'meta_tag',
    'salon',
    'message',
    'faq',
    'gallery',
    'social',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': decouple.config('DEFAULT_DB_ENGINE') or 'django.db.backends.sqlite3',
        'NAME': decouple.config('DEFAULT_DB_NAME') or BASE_DIR / 'db.sqlite3',
        'USER': decouple.config('DEFAULT_DB_USER'),
        'PASSWORD': decouple.config('DEFAULT_DB_PASSWORD'),
        'HOST': decouple.config('DEFAULT_DB_HOST'),
        'PORT': decouple.config('DEFAULT_DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/backend/static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/backend/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = decouple.config('EMAIL_HOST')
EMAIL_PORT = decouple.config('EMAIL_PORT')
EMAIL_HOST_USER = decouple.config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = decouple.config('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = decouple.config('EMAIL_USE_SSL') == 'True'
EMAIL_USE_TLS = decouple.config('EMAIL_USE_TLS') == 'True'
FROM_EMAIL = decouple.config('FROM_EMAIL')

MANAGERS = [manager.strip() for manager in decouple.config('MANAGERS').split(',')]

BASE_URL = decouple.config('BASE_URL')

CORS_ALLOWED_ORIGINS = [origin.strip() for origin in decouple.config('CORS_ALLOWED_ORIGINS').split(',')]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in decouple.config('CSRF_TRUSTED_ORIGINS').split(',')]

TELEGRAM_BOT_TOKEN = decouple.config('TELEGRAM_BOT_TOKEN')

# Group chat id, where bot sends notifications
TELEGRAM_GROUP_CHAT_ID = decouple.config('TELEGRAM_GROUP_CHAT_ID')

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'sourceEditing', ],
    },
}
