import {ShantellSans, EvolventaRegular} from "@/app/fonts";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Image from "next/image";

import '@/styles/bootstrap-grid.css';
import "@/styles/reset.css";
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import "@/styles/globals.css";


export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({children}) {
   return (
      <html lang="uk">
      <body className={`${EvolventaRegular.variable} ${ShantellSans.variable}`}>
      <Image
         width={92}
         height={481}
         src="/img/body-stripe-vertical.png"
         alt="Дитяча перукарня"
         className="body-stripe-vertical"
      />
      <Header/>
      {children}
      <Footer/>
      </body>
      </html>
   );
}