import {ShantellSans, EvolventaRegular} from "@/app/fonts";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import '@/styles/bootstrap-grid.css';
import "@/styles/reset.css";
import "@/styles/globals.css";


export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({children}) {
   return (
      <html lang="uk">
      <body className={`${EvolventaRegular.variable} ${ShantellSans.variable}`}>
      <Header/>
      {children}
      <Footer/>
      </body>
      </html>
   );
}