# Generated by Django 5.0.6 on 2024-08-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_day_schedule'),
        ('staff', '0003_alter_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='staff.staff'),
        ),
    ]
