# Generated by Django 5.0.6 on 2024-10-21 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_day_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.salon')),
            ],
        ),
    ]
