# Generated by Django 5.0.6 on 2024-10-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_salonphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonphone',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
