# Generated by Django 5.0.6 on 2024-10-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_alter_salonphone_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salonphone',
            unique_together={('salon', 'phone')},
        ),
    ]
