# Generated by Django 5.0.6 on 2024-10-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_alter_salonphone_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
