# Generated by Django 5.0.6 on 2024-10-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='salonphone',
            name='phone_iso',
            field=models.CharField(default='', max_length=255),
        ),
    ]
