# Generated by Django 5.0.6 on 2024-09-03 22:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='faq-icons/')),
            ],
        ),
    ]
